apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: hetzner-failoverip-controller
    app.kubernetes.io/component: controller
    control-plane: controller
  name: hetzner-failoverip-controller
  namespace: hetzner-fip-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hetzner-failoverip-controller
      app.kubernetes.io/component: controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hetzner-failoverip-controller
        app.kubernetes.io/component: controller
    spec:
      containers:
        - name: controller
          env:
            - name: RUNTIME_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TMPDIR
              value: /tmp
            - name: ROBOT_API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hetzner-failoverip-controller
                  key: username
            - name: ROBOT_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hetzner-failoverip-controller
                  key: password
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  resource: requests.memory
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          image: ghcr.io/cit-consulting/hetzner-failoverip-controller:0.9.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 300m
              memory: 32Mi
            requests:
              cpu: 30m
              memory: 24Mi
          volumeMounts:
            - name: temp
              mountPath: /tmp
            - name: shell-operator-run
              mountPath: /var/run/shell-operator
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          livenessProbe:
            timeoutSeconds: 5
            httpGet:
              port: 9115
              path: /
              scheme: HTTP
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      serviceAccountName: hetzner-failoverip-controller
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      terminationGracePeriodSeconds: 10
      volumes:
        - name: temp
          emptyDir:
            sizeLimit: 100M
        - name: shell-operator-run
          emptyDir:
            sizeLimit: 10M
