---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-hetzner-failoverip-controller
rules:
  - apiGroups: [ "hetzner.citc.dev" ]
    resources: [ "failoverippolicies" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "" ]
    resources: [ "services", "namespaces" ]
    verbs: [ "get" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-hetzner-failoverip-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-hetzner-failoverip-controller
subjects:
  - kind: ServiceAccount
    name: hetzner-failoverip-controller
    namespace: hetzner-fip-system
