apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: failoverippolicies.hetzner.citc.dev
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: hetzner.citc.dev
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: failoverippolicies
    # singular name to be used as an alias on the CLI and for display
    singular: failoverippolicy
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: FailoverIpPolicy
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - hfip
    #  preserveUnknownFields: false
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                getFailoverIpCommand:
                  type: string
                getTargetServerMainIpCommand:
                  type: string
                dryRun:
                  type: boolean
                  default: false
              required:
                - getFailoverIpCommand
                - getTargetServerMainIpCommand
                - dryRun
