apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hetzner-fip-system

resources:
- etl-namespace.yaml
- hetzner-failover-api-policy-crd.yaml
- service-account.yaml
- crd-rbac.yaml
- controller-deployment.yaml
